### ISSUE TITLE
URGENT: timingController.registerFrameCallback doesn't work with multiple same widgets

### ISSUE THREAD

**Issue by pvanallen** [netlabtoolkit/ntk#106]
When I use window.app.timingController.registerFrameCallback(this.timeKeeper, this) in a widget, it stops working when another of the same widget is added to the stage. The new widget works fine. 

For example, the CloudIn and CloudOut widgets both use timingController. If a CloudIn is added to the stage, and then another CloudIn is added, the first one stops getting timing callbacks. CloundIn and CloudOut can coexist just fine.

**Comment by scazan** [comment]
Was using the prototype function to check against existence rather than an instance function
