### ISSUE TITLE
Complex patch does not import correctly

### ISSUE THREAD

**Issue by pvanallen** [netlabtoolkit/ntk#107]
Complex patches with many widgets connected together do not import correctly. Here are the problems:

1. the wires do not seem to be connected - it is hard to tell if the are not visible or not connected
2. widgets that are off to the right of the visible canvas do not render correctly - e.g. outlets fall off the right side and show below the bottom of the widget, breaking the more div
3. sometimes all the wires connect to one single widget

Note that when loaded up, all of the widgets are off to the right of the default size of the window.

Example patch is attached. 
[complexPatch.ntk.zip](https://github.com/netlabtoolkit/ntk/files/123993/complexPatch.ntk.zip)

**Comment by pvanallen** [comment]
The attached patch does not load correctly and what's interesting is that the first two widgets listed in the patch have the same "wid" of c19. This must mean that either editing the patch on the original computer, or when it was exported, the ID got accidentally duplicated. I wonder if that happens when there is a lot of adding and deleting of widgets?
[littlesun-patch.ntk.zip](https://github.com/netlabtoolkit/ntk/files/226355/littlesun-patch.ntk.zip)

**Comment by scazan** [comment]
That seems to be an issue in both patches. I have an idea why that might be (having to do with Backbone's assignment of those ids).

**Comment by scazan** [comment]
Added new id system and currently testing this.

**Comment by scazan** [comment]
New id system seems to be humming along so far. This should fix any further issues like this in the future.
