### ISSUE TITLE
URGENT: Multiple servos can't move at the same time

### ISSUE THREAD

**Issue by pvanallen** [netlabtoolkit/ntk#115]
There is a consistent issue that prevents more than one servo moving at the same time. For example, if an AnalogIn is connected to two Servo widgets, only one will move. The one that moves is always the higher port. For example, if servo widgets are connected to D3 and D5 and try to move at the same time, only D5 will move. But if D5 is not receiving any move commands, then D3 can move.
<img width="497" alt="pasted_image_10_7_16__3_34_pm" src="https://cloud.githubusercontent.com/assets/1456334/19207208/8841b7b6-8ca3-11e6-90a8-fec6c6775f71.png">

**Comment by pvanallen** [comment]
The same thing happens with AnalogOut. I.e. the highest Port takes precedence from lower ports.

**Comment by scazan** [comment]
Hi Phil,

Hmm.. I will take a look at it right now.

**Comment by pvanallen** [comment]
I should mention that this is in the 1.1.1 APP version that was released June 14th.

**Comment by scazan** [comment]
Can I just verify with what I'm seeing on my end? 

I'm seeing that it works on both servos as long as the AnalogIn is enabled. When I disable the AnalogIn and try to control with the mouse I am seeing that the only one of the servos works.

**Comment by pvanallen** [comment]
checking...

**Comment by pvanallen** [comment]
Yes, I see the same thing.

**Comment by scazan** [comment]
Thanks! Trying to figure out why that would be different now.

**Comment by scazan** [comment]
Can you try the latest and see if that fixes it for you?

**Comment by netlabtoolkit** [comment]
I’m trying the 1.1.0 branch, but can’t test because it has the old problem with the Edit On button - i.e. clicking on the button does not switch from Off to On. You fixed that in dev on August 11th (556bfc98b357a4902bff2b71ee7c69864ab9771f) - I tried just applying that fix manually, but it didn’t help.

.phil

**Comment by scazan** [comment]
That happened to me when I switched to 1.1.0 as well until I ran "npm
install"  in the main directory as well as the server directory. That might
be the issue.

**Comment by pvanallen** [comment]
Okay, got it working. That seems to have fixed the #115 issue. Great!

Can you merge this fix with the version 1.1.1 version of June 13th? That is what we have currently released - it fixes a lot of major issues with patch saving/loading.

.phil

**Comment by pvanallen** [comment]
Thanks again for fixing the bug. I'd like to get a release out Monday with this fix integrated with 1.1.1. I can do the electron app build if you can do the merge. That possible?
