### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by gbaumgart** [netlabtoolkit/ntk#120]
hi,
is there a specific license for the server & client side code ? I might be interested to fully integrate ntk in my [IDE](https://github.com/net-commander/windows-dist/issues/57) as an alternative block language. That's because you're also using AMD modules and I like your project :-)

thanks a lot!
g

**Comment by gbaumgart** [comment]
never mind, just figured that the 'server' is done via phantom. makes it pretty hard to integrate anyhows.

**Comment by scazan** [comment]
Hi gbaumgart! The server is actually written in Node. We use phantom as a way of keeping everything that was running on the front-end when a user was interacting with it, running the same on the backend. We are hoping to move away from that but this might actually cause us to switch over to CommonJS to easier advantage of shared code.

**Comment by gbaumgart** [comment]
Hi Scott, not sure you know but you actually can have AMD modules running on server/client side. I do this all over the place and brings you a step closer to have all code isomorphic. Dojo's and require-js AMD loader allows that. It just needs some tiny adjustments in the imports, see [here:](https://github.com/net-commander/example-workspace/blob/master/drivers/Raspberry/PI-GPIO.js#L8)

```
define([
    "dcl/dcl",
    'xdojo/has',
    "xdojo/has!host-node?nxapp/protocols/ProtocolBase" <-- will be loaded only on server side
    "xdojo/has!host-node?dojo/node!yargs-parser"            <-- load a CJS module
```

it looks a bit ugly but its still better than going into the hell of transpilers and what not (i like it simple ;-). IBM wrote a 'has' plugin too: https://github.com/ibm-js/requirejs-dplugins. Never tried this for NodeJS but it should work since most of their client libraries (widget framework) work fantastic within nodejs as well (jsdom).

Then sometimes you may want use functions on the client from a AMD module which was meant for server only: 

define([
    "dojo/node!xcf-server-misc/serialport"  <-- this unchecked import would fail
    "..."
]

But this nodejs import you could noob out if you [adjust the "dojo!node"](https://github.com/gbaumgart/x-dojo/blob/master/node.js#L61) plugin which detects where it runs. 

Now this all is a little hacky but when writing authoring software, AMD turns out as the best module format since you can easily add search paths but also re-requiring modules (hot-reloading user modules with require.undef). The real challenges start when you want to synchronize states between server/client but yet, since its the same code under the hood, its relative easy.


Ok, wasn't meant to get that long, just a motivation since you are closer to 'ideal' with AMD than you may think :-)

**Comment by gbaumgart** [comment]
if you need help with setting this up with dojo let me know, its a little shaky to get this running.

**Comment by gbaumgart** [comment]
ok, i guess there is no interest to be integrated in something else. back to node-red :-)
g

**Comment by gbaumgart** [comment]
never mind, it was a amazing great and a real pleasure talking to you.

**Comment by pvanallen** [comment]
Hey gbaumgart,

Phil van Allen here - sorry for the delayed response. Can you say more about what you want to do and what you would need from us?

.phil

**Comment by gbaumgart** [comment]
right, actually just need you to put a license on it. i would start trying to integrate it and possibly also rewrite some things, at least to make 'phantom' go away. and if you like the fork, well, something in return for you then.

thanks a lot,
g

**Comment by pvanallen** [comment]
Got it. Any preferences for license? 

Also, FYI there are several changes underway or planned to improve the system in addition to getting rid of phantom - e.g.

Redoing the hardware system to be more generic and support a range of hardware (in progress)
Implementing a formal way of layering elements on the screen

.phil

**Comment by gbaumgart** [comment]
well, i am always using the more liberal BSD, just to make sure no one has any sort of trouble. It's hard to say what your intentions are but MIT/BSD or even LGPL is fine with me. 

nice to hear about the progress. i gonna wait then a little :-)
thanks a thousand
