### ISSUE TITLE
Add support for OSC for generic OSC widget

### ISSUE THREAD

**Issue by pvanallen** [netlabtoolkit/ntk#20]
Widget specifies OSC url to listen to, with wildcards and parameter number - also ability to transmit all parameters to another widget.

Kinect support http://www.tsps.cc

See also NETLab Toolkit Flash documentation: http://www.netlabtoolkit.org/learning/tutorials/osc/

**Comment by scazan** [comment]
OSC in/out working. Need to add in wildcards.
