### ISSUE TITLE
npm ERR! Failed at the gaze@0.6.4 install script 'node-gyp rebuild'

### ISSUE THREAD

**Issue by marcusguttenplan** [netlabtoolkit/ntk#74]
Issue with npm installation, log looks normal until it hits gaze, where it outputs:

```/node_modules/gaze
1208 verbose stack Error: gaze@0.6.4 install: `node-gyp rebuild`
1208 verbose stack Exit status 1
1208 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
1208 verbose stack     at EventEmitter.emit (events.js:110:17)
1208 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
1208 verbose stack     at ChildProcess.emit (events.js:110:17)
1208 verbose stack     at maybeClose (child_process.js:1015:16)
1208 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
1209 verbose pkgid gaze@0.6.4
1210 verbose cwd /Applications/ntk
1211 error Darwin 14.4.0
1212 error argv "node" "/usr/local/bin/npm" "update"
1213 error node v0.12.7
1214 error npm  v2.11.3
1215 error code ELIFECYCLE
1216 error gaze@0.6.4 install: `node-gyp rebuild`
1216 error Exit status 1
1217 error Failed at the gaze@0.6.4 install script 'node-gyp rebuild'.
1217 error This is most likely a problem with the gaze package,
1217 error not with npm itself.
1217 error Tell the author that this fails on your system:
1217 error     node-gyp rebuild
1217 error You can get their info via:
1217 error     npm owner ls gaze
1217 error There is likely additional logging output above.
1218 verbose exit [ 1, true ]
1219 verbose unbuild node_modules/gaze
1220 info preuninstall gaze@0.6.4
1221 info uninstall gaze@0.6.4
1222 verbose unbuild rmStuff gaze@0.6.4 from /Applications/ntk/node_modules
1223 info postuninstall gaze@0.6.4
1224 silly gentlyRm /Applications/ntk/node_modules/gaze is being purged from base /Applications/ntk
1225 verbose gentlyRm don't care about contents; nuking /Applications/ntk/node_modules/gaze
1226 silly vacuum-fs purging /Applications/ntk/node_modules/gaze
1227 silly vacuum-fs quitting because other entries in /Applications/ntk/node_modules
```

At first I thought my `$PATH` may have gotten tweaked, but npm runs in other application folders just fine.

**Comment by scazan** [comment]
Hi Marcus,

Thanks for the bug report. It looks like you running OSX. Have you installed the XCode command line tools in the past?

Also, as a temporary workaround, you could simply remove the gaze line in the devDependencies section of package.json. This is only needed for the live reload server during development.

**Comment by marcusguttenplan** [comment]
It's a pretty fresh install of OSX, with command line tools, homebrew, and node compiled from source. Removing gaze solves the bug, but I was worried about the `$PATH` because in the past there have been metadata corruption issues that interfered with developer tools. Since fresh installing OSX, the `$PATH` is `/Users/username/.rbenv/shims:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin`, if that is of use.

**Comment by pvanallen** [comment]
I think this may have to do with if you have node-gyp installed or not. I don't think it gets installed by the Xcode command line tools.

**Comment by scazan** [comment]
Hmm.. ok. It is not installed by Xcode but it depends on Xcode's command
line tools being installed (on Mac). I thought it was installing as a
dependency of the serial library but perhaps we need an explicit node-gyp
dependency in package.json.

On Tue, Aug 18, 2015 at 3:30 PM, Philip van Allen <notifications@github.com>
wrote:

> I think this may have to do with if you have node-gyp installed or not. I
> don't think it gets installed by the Xcode command line tools.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/netlabtoolkit/ntk/issues/74#issuecomment-132375556>.
>



-- 
Scott
http://www.scottcazan.com
https://soundcloud.com/scottcazan
Twitter: @scazan

**Comment by marcusguttenplan** [comment]
I tried a few different ways to get first node-gyp and then gaze to work, but am still getting [errors](https://gist.github.com/marcusguttenplan/b2429ee183a413c8b40a).

First was to add node-gyp to the package.json so it would install with npm install, but threw "install node-gyp globally with npm install node-gyp -g." 

Tried that and that threw "install node-gyp rebuild", which globally installed also does not work. The output of `npm install --verbose` is [here](https://gist.github.com/marcusguttenplan/9722bbbfdb94f74eacc0), and at line 697 shows that `nan` module in the `serialport` module in the `johnny-five` module is having issues with this:

```
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
  c++ '-DNODE_GYP_MODULE_NAME=pathwatcher' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/Users/marcusguttenplan/.node-gyp/0.12.7/src -I/Users/marcusguttenplan/.node-gyp/0.12.7/deps/uv/include -I/Users/marcusguttenplan/.node-gyp/0.12.7/deps/v8/include -I../src -I../node_modules/nan  -Os -gdwarf-2 -mmacosx-version-min=10.5 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -fno-rtti -fno-exceptions -fno-threadsafe-statics -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/pathwatcher/src/main.o.d.raw  -c -o Release/obj.target/pathwatcher/src/main.o ../src/main.cc
```

After looking at some similar issues, I made sure node was using the correct python from the correct location and installed `libtools` with brew. Still no luck.

Reverted back to removing gaze from package.json and it works fine! Looks like node-gyp might just be a weak module.

**Comment by netlabtoolkit** [comment]
Thanks for the update. So have you actually run NTK?

**Comment by marcusguttenplan** [comment]
Yes, I haven't tried it with any boards yet, but seems to work fine.
