### ISSUE TITLE
Need a way to start NTK and erase current patch

### ISSUE THREAD

**Issue by pvanallen** [netlabtoolkit/ntk#82]
There are times when the current patch causes a hang or other problem, and there needs to be a way to start NTK with a default, clear patch. This is especially true for the stand-alone version running from the server directory.

In addition if currentPatch.nlp is deleted, this causes an error, and you can't use the authoring system. The system should replace a not found file with the default clear patch.

E.g. npm run reset

**Comment by scazan** [comment]
Added 'npm run reset' to erase the current patch file. Fixed the second issue of missing currentPatch as well.
